[book]
authors = ["Phodal Huang"]
language = "en"
multilingual = false
src = "src"
title = "AI 辅助软件工程：实践与案例解析"

[output.html]
git-repository-url = "https://github.com/phodal/aise"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/phodal/aise/edit/master/{path}"
site-url = "/"
cname = "aise.phodal.com"
additional-css = ["theme/custom.css"]